AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31

###############################################################################
# GLOBALS
###############################################################################
Globals:
  Function:
    Runtime: python3.12
    Timeout: 10
    MemorySize: 256
    Layers:
      - !Ref CommonLayer       # Todas las Lambdas heredan la capa

###############################################################################
# API HTTP
###############################################################################
Resources:

  HttpApi:
    Type: AWS::Serverless::HttpApi
    Properties:
      StageName: Prod
      CorsConfiguration:
        AllowOrigins: ["*"]
        AllowMethods: [POST]
        AllowHeaders: [Content-Type, Authorization]

###############################################################################
# LAYER con código compartido
###############################################################################
  CommonLayer:
    Type: AWS::Serverless::LayerVersion
    Properties:
      LayerName: demo-common-layer
      ContentUri: layer/          # debe contener requirements.txt y python/
      CompatibleRuntimes: [python3.12]
    Metadata:
      BuildMethod: python3.12     # SAM instalará requirements.txt en la layer

###############################################################################
# FUNCIÓN /login (POST)
###############################################################################
  LoginFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/handlers_public        # solo el handler
      Handler: login_post.lambda_handler  # login_post.py en esa carpeta
      Layers:
        - !Ref CommonLayer               # referencia explícita (redundante pero segura)
      Environment:
        Variables:
          JWT_SECRET: "dev_secret"
          JWT_ALGORITHM: "HS256"
      Events:
        HttpApiLogin:
          Type: HttpApi
          Properties:
            ApiId: !Ref HttpApi
            Path: /login
            Method: POST

###############################################################################
# OUTPUTS
###############################################################################
Outputs:
  ApiBaseUrl:
    Description: "URL base del API local/AWS"
    Value: !Sub "https://${HttpApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/"
  LoginUrl:
    Description: "Endpoint de login"
    Value: !Sub "https://${HttpApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/login"
