AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31

Globals:
  Function:
    Timeout: 10
    Runtime: python3.13
    MemorySize: 256

Resources:

  MyHttpApi:
    Type: AWS::Serverless::HttpApi
    Properties:
      StageName: Prod
      CorsConfiguration:
        AllowOrigins:
          - "*"
        AllowMethods:
          - GET
          - POST
          - PUT
          - DELETE
        AllowHeaders:
          - Content-Type
          - Authorization

  TemplatesFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: .
      Handler: app.lambda_handler

      Environment:
        Variables:
          MONGODB_DB_NAME: "db_demo"
          JWT_SECRET: "46ae6e4f0vatkjkj0hfsm15sqt"
          JWT_ALGORITHM: "HS256"
          MONGODB_URI: "mongodb+srv://db_vinks_integrations:KLJP9B6lfonqeu9O@cluster-vinks-red.lntwg7s.mongodb.net/dbname?retryWrites=true&w=majority&tls=true"
      Events:
        GetAuth:
          Type: HttpApi
          Properties:
            ApiId: !Ref MyHttpApi
            Path: /
            Method: GET
        GetAuthById:
          Type: HttpApi
          Properties:
            ApiId: !Ref MyHttpApi
            Path: /{id}
            Method: GET
        CreateAuth:
          Type: HttpApi
          Properties:
            ApiId: !Ref MyHttpApi
            Path: /
            Method: POST
        UpdateAuth:
          Type: HttpApi
          Properties:
            ApiId: !Ref MyHttpApi
            Path: /{id}
            Method: PUT
        DeleteAuth:
          Type: HttpApi
          Properties:
            ApiId: !Ref MyHttpApi
            Path: /{id}
            Method: DELETE
        # Public Create Auth
        PublicCreateAuth:
          Type: HttpApi
          Properties:
            ApiId: !Ref MyHttpApi
            Path: /public
            Method: POST



Outputs:
  # URL para invocar el endpoint GET /auth
  TemplatesApiUrl:
    Description: "Invoke URL para el recurso /auth"
    Value: !Sub
      - "https://${ApiId}.execute-api.${Region}.amazonaws.com/${StageName}/auth"
      - ApiId: !Ref MyHttpApi
        Region: !Ref AWS::Region
        StageName: Prod
